version: '{build}'

platform:
  - x64

services:
  - mssql2017

shallow_clone: true

environment:
  matrix:
    - { NODE_VERSION: 10, DIALECT: mssql }

install:
  - ps: Install-Product node $env:NODE_VERSION x64
  - ps: |
      $pkg = ConvertFrom-Json (Get-Content -Raw package.json)
      $pkg.dependencies.PSObject.Properties.Remove('sqlite3')
      $pkg.dependencies.PSObject.Properties.Remove('pg-native')
      ConvertTo-Json $pkg | Out-File package.json -Encoding UTF8
  - npm install

build: off

before_test:
  - ps: . .\test-env-setup\scripts\appveyor-setup.ps1

test_script:
  - 'npm run test1'
